#!/bin/sh

sudo apt-get install \
  build-essential git curl python-setuptools python-dev \
  ruby vim emacs zsh tmux terminator xclip \
  compizconfig-settings-manager compiz-plugins-extra bison silversearcher-ag \
  htop exfat-utils exfat-fuse

# Good ol' terminal-style vim doesn't have access to the clipboard,
# which is a part of the X windows system. Installing vim-gtk gives vim
# the access that it needs to modify and view the clipboard.
sudo apt-get install vim-gtk

# Install oh-my-zsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

# Create .customrc which will be used for local customization
touch "$HOME/.customrc"

# Clone dotfiles~
if [ -z "$REPO_DIR" ]; then
  REPO_DIR="$HOME/repositories"
fi

mkdir -p "$REPO_DIR"
cd "$REPO_DIR"
git clone https://github.com/sendyhalim/dotfiles
cd dotfiles
rm ~/.zshrc
./create_ln.sh

# Clone vimrc
cd "$REPO_DIR"
git clone https://github.com/sendyhalim/vimrc
cd vimrc
./create_ln.sh

# Install spacemacs
git clone https://github.com/syl20bnr/spacemacs "$HOME/.emacs.d"

# Install vim vundle
git clone https://github.com/VundleVim/Vundle.vim.git "$HOME/.vim/bundle/Vundle.vim"

# Install linuxbrew
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install)"

# Install linuxbrew wrapper so that we can use the `brew` command in the shell
sudo apt-get install linuxbrew-wrapper

# Install NVM
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.31.2/install.sh | zsh

# Install GVM
curl -o- https://raw.githubusercontent.com/moovweb/gvm/master/binscripts/gvm-installer | zsh

# Install powerline fonts, beauty at its best!
git clone https://github.com/powerline/fonts powerline-fonts
cd powerline-fonts
./install.sh
cd .. && rm -r powerline-fonts

# Setup hotkeys
# -------------------------------------------
. ./shortcuts
. ./aliases
