#!/bin/sh

# Setup hotkeys for media keys
# Documentation at `Documentation/Shortcuts.md`
gsettings set org.gnome.settings-daemon.plugins.media-keys volume-up "<Super>equal"
gsettings set org.gnome.settings-daemon.plugins.media-keys volume-down "<Super>minus"
gsettings set org.gnome.settings-daemon.plugins.media-keys stop "<Super>Backspace"
gsettings set org.gnome.settings-daemon.plugins.media-keys play "<Super>Return"
gsettings set org.gnome.settings-daemon.plugins.media-keys previous "<Super>comma"
gsettings set org.gnome.settings-daemon.plugins.media-keys next "<Super>period"

